apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-automation-backend
  namespace: whatsapp-system
  labels:
    app: whatsapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-backend
  template:
    metadata:
      labels:
        app: whatsapp-backend
    spec:
      # This allows k3s to pull from your private Docker Hub repo
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backend
          image: ezdussin/whatsapp-automation-backend:latest
          # Always check for a newer version of 'latest' on every restart
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            # Database Config
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SUPABASE_KEY

            # Evolution API Config
            - name: EVOLUTION_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: EVOLUTION_URL
            - name: EVOLUTION_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: EVOLUTION_KEY
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-backend-service
  namespace: whatsapp-system
spec:
  selector:
    app: whatsapp-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP